yes
threw exception: univ_cons(software_error("call to compare/3 for non-canonical type `user_defined_equality_1.foo\'"))
threw exception: univ_cons(software_error("call to compare/3 for non-canonical type `user_defined_equality_1.foo\'"))
